name: computer-vision-env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9.6
  - matplotlib=3.4.2
  - pandas=1.5.3
  - numpy=1.20.3
  - tqdm=4.65.0
  - pip=23.3
  - pip:
      - opencv-contrib-python==4.5.1.48
